### ISSUE TITLE
Parts without dedicated DR compatibility patch can have Ablator instead of AblativeShielding

### ISSUE THREAD

**Issue by Gordon-Dry** [Starwaster/DeadlyReentry#40]
These parts are properly patched by DR to have a ModuleHeatShield instead of a ModuleAblator, but the ablativeResource still is Ablator.

Example:
Bluedog_DB Gemini Heatshield.

What is missing is a final patch (or kinda zzzz_DeadlyReentry) to properly convert all heathshields.

**Comment by Starwaster** [comment]
If Bluedog parts are configured to use Ablator resource then that should not be changed. Are you suggesting it SHOULD be changed? To AblativeShielding for instance? If anything I need to go through the configs and make sure that doesn't happen elsewhere. Only DRE parts should be using that resource. Other mod's that use a different resource should be left that way or they will encounter errors if they uninstall DRE. (this doesn't matter for DRE parts using that resource because any craft in the field using those parts will cease to exist)

Consider the following scenario:

- Player installs both Bluedog and Deadly Reentry. Order does not matter.
- Player launches craft with Bluedog heatshield part.
- Player uninstalls Deadly Reentry. _If_ DRE had patched his Bluedog heatshields to use DRE AblativeResource and he has craft in the field, KSP will now begin throwing errors when the player tries to view that craft in the map. That's a KSP bug btw and they probably should do some sanity checking for missing resources.
