### ISSUE TITLE
Reentry very not deadly

### ISSUE THREAD

**Issue by duqueisa** [Starwaster/DeadlyReentry#50]
In the newest versions of KSP a 1mill km apoapsis to a 20km periapsis on kerbin uses one unit of ablator. Is there a new patch coming soon or a way I can tweak the file to make it more realistic
I am using 1.11.2

**Comment by Starwaster** [comment]
I just performed a reentry using a Mk 1-3 command module and matching 2.5m stock heat shield and ended up with 493 units of ablator remaining.

My reentry used the same parameters you defined and I ended up with 502 units remaining (298 used up)

If you get radically different results with the same craft design (I don't know what your craft was like) then it's an issue with your settings or another mod. (note that if using Realism Overhaul that it drastically reduces the amount of ablator consumed because historically only a small amount of ablator _was_ consumed)

**Comment by Starwaster** [comment]
Closing this as unable to replicate and no further feedback for a week.
