### ISSUE TITLE
Explode on reentry

### ISSUE THREAD

**Issue by LiTe1991** [Starwaster/DeadlyReentry#59]
Hi,
I`m using deadly reentry with Near Future Spacecraft. 
If I try to reenter with the Lander Command Pods and two heat shield, my spacecraft explode with the info that it's overheating. But if I check the temp over the sensor tab, there the temp is under the max temp.
It's a orbit with 1500000km appo and 32-35km perep with a speed of 2800-2900m/s.

**Comment by Starwaster** [comment]
I'm not familiar with the NF spacecraft pack so I'm not sure what command pod you're referring to. Some screenshots of the reentry craft would help. The shape of the pod could be an issue. If it's not a tapered/conical pod then part of the pod is probably being exposed to the reentry shockwave. Shape matters when checking if one part occludes another (such as the heat shield occluding the pod)

For instance, if it's the pod at the far right in this image:
https://i.imgur.com/d1RrrdE.png

Then the heat shield will need to be wider than the base of the pod or it will not give adequate protection. Adding extra shields probably wouldn't help.

Second, the temperature sensor isn't really helpful in this situation because it only tells you the internal temperature of the sensor part and not the status of the part it is attached to.

Parts also have a skin temperature associated with them which has its own max temperature rating. If the skin gets too hot then the part will be destroyed. I suspect that it is the pod's skin temperature which is failing. You can view part temperature debugging by going into the console menu (alt-F11 I think) and enabling thermal debugging under physics.

**Comment by LiTe1991** [comment]
This is the entry ship and I will check it with the debug settings, good to know with the skin temp
![20220418212347_1](https://user-images.githubusercontent.com/20238860/163864673-c6e09b01-a38c-455a-8d0d-f329daba033d.jpg)

**Comment by Starwaster** [comment]
Ok so it’s got a generally conic shape which is good but that shield is way too small. There’s too much of the pod exposed. 

I’m assuming that NF doesn’t have a matching shield for it?

Procedural Parts has resizable shields if you have it or want to install it. 

I could also include a patch in DR that adds a small amount of shielding to that pod. The Mk1-2 pod has ten units of shields. That much might be enough

**Comment by LiTe1991** [comment]
I was not able to find a extra one or one which fit better and I also create a video with temp overlay.
I would say your assumption sounds right. 
https://drive.google.com/file/d/1KPYOAeQUAno-Cx5Qjwk4vcOYuyICCIQW/view?usp=sharing

**Comment by LiTe1991** [comment]
> Ok so it’s got a generally conic shape which is good but that shield is way too small. There’s too much of the pod exposed. I’m assuming that NF doesn’t have a matching shield for it? Procedural Parts has resizable shields if you have it or want to install it. I could also include a patch in DR that adds a small amount of shielding to that pod. The Mk1-2 pod has ten units of shields. That much might be enough
> […](#)
> On Apr 18, 2022, at 3:26 PM, LiTe1991 ***@***.***> wrote: ﻿ This is the entry ship and I will check if with the debug settings, good to know with the skin temp — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

Procedural Parts work`s fine for the problem, but it looks a little bit funny :-D
Maybe a patch with a little bit ablator for MK1-2 would be also nice or would be than deadly reentry not deadly enough?

**Comment by Starwaster** [comment]
I don't know if you saw, but I added a new patch file supporting NF pods. I haven't done a new release but you can grab the file here:
https://github.com/Starwaster/DeadlyReentry/raw/working/DeadlyReentry/DeadlyReentry-NearFuture.cfg

(right click the link and select download as. Save it to the GameData/DeadlyReentry folder of your installed game)

**Comment by LiTe1991** [comment]
Sounds good.
I will try it out and give you a feedback :-)

**Comment by LiTe1991** [comment]
Sry for the late answer.
Your changes works fine, problem is now fixed.
